build:
	docker buildx build --platform linux/amd64 -t europe-west3-docker.pkg.dev/cwregistry/base/java11:jre-alpine-20231113 .

push:
	docker push europe-west3-docker.pkg.dev/cwregistry/base/java11:jre-alpine-20231113
