build:
	docker buildx build --platform linux/amd64 -t europe-west3-docker.pkg.dev/cwregistry/base/golang:alpine3204-runtime .

push:
	docker push europe-west3-docker.pkg.dev/cwregistry/base/golang:alpine3204-runtime
